### PR TITLE
Added MatchOnlyRunAutomaton

### PR DESCRIPTION
**Pull request by turf00**
+ This provides linear time based on the input length for searching a String for a substring match with an Automaton.
+ There is no support with this for finding the start, end matching pos. Simply whether a match happens or not.
+ Also added Junit 5 and some tests for MatchOnlyRunAutomaton and RunAutomaton.

### CODE REVIEW

**Comment by turf00** [comment]
I cannot share all the performance tests we did but for cases where there is a partial match, then fail and the AutomatonMatcher has to then backtrack a lot we see much better throughput.

Note all tests are with jmh and attempting to avoid the pitfalls of perf testing, we hope!

The following are in operations/s, tested on an Intel 2.4 GHz i9

| Scenario|AutomatonMatcher | MatchedOnlyRunAutomaton |
| ------------- | ------------- | ------------- |
|  CHAR_10K_NOT_MATCH_IS | 8.824 | 45,780.349 |
|  CHAR_100K_NO_MATCH_CS | 0.092 | 4,547.675 |

**Comment by turf00** [comment]
@amoeller Are you going to have time to review this PR?

**Comment by amoeller** [comment]
Thanks, Justin!

**Review by ghost — COMMENTED** [review]
66996870

**Pull request merged**
